c_compiler:
  - vs2022            # [win]
  - gcc               # [linux]
cxx_compiler:
  - vs2022            # [win]
  - gxx               # [linux]
channel_sources:
  - conda-forge
MACOSX_SDK_VERSION:   # [osx]
  - "10.15"           # [osx]
  