{% set version = "2025.2.0a3" %}

package:
  name: iris-codec
  version: {{ version }}

source:
  url: https://github.com/IrisDigitalPathology/Iris-Codec/archive/refs/tags/2025.2.0a3.tar.gz
  sha256: 8b6ca82459da6415bf90792b80a8dd947859632b755362e0f213df91680f132e
build:
  number: 1
  run_exports:
    - {{ pin_subpackage('iris-codec', max_pin='x.x') }}
    - libjpeg-turbo
    - libavif
    - libpng
  missing_dso_whitelist:
    - '*/libopenslide.1.*' # Eventually remove reliance on OpenSlide


requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake
    - make                    # [not win]
    - ninja                   # [win]
    - pybind11
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               
  host:
    - python
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               
  run:
    - python
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               


test:
  imports:
   - Iris


about:
  home: https://github.com/IrisDigitalPathology/Iris-Codec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Portable and blazingly fast whole slide image compression and serialization library for the Iris File Extension
  dev_url: https://github.com/IrisDigitalPathology/Iris-Codec
  description: |
    The Iris Codec Community module is a part of the Iris Digital Pathology project. 
    This module allows for the reading and writing of Iris whole slide image (WSI) digital slide files (.iris) and 
    allows for the decoding of Iris Codec-type compressed tile image data. This repository was designed to allow 
    for extremely fast slide access using what we consider a very simple API as we want to simplify access to these
    files for you. Please see <https://github.com/IrisDigitalPathology/Iris-Codec> for more information.

extra:
  feedstock-name: Iris-Codec
  recipe-maintainers:
    - ryanlandvater
