{% set version = "2025.3.1" %}

package:
  name: iris-codec
  version: {{ version }}

source:
  url: https://github.com/IrisDigitalPathology/Iris-Codec/archive/refs/tags/2025.3.1.tar.gz
  sha256: dadaf8cda0c6f98f2cd02b49a57c7afae56fdbcf2228ec35813f98529953ae87
build:
  number: 2
  run_exports:
    - {{ pin_subpackage('iris-codec', max_pin='x.x') }}
    - libjpeg-turbo
    - libavif
    - libpng
  missing_dso_whitelist:
    - '*/libopenslide.1.*' # Eventually remove reliance on OpenSlide


requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake
    - meson
    - make                    # [not win]
    - ninja
    - pkg-config                            
    - pybind11
    - libhwy
    - libjpeg-turbo 
    - libavif
    - libpng
    - libdicom
    - openslide               
  host:
    - python
    - libhwy
    - libjpeg-turbo 
    - libavif
    - libpng
    - libdicom
    - openslide               
  run:
    - python
    - libhwy
    - libjpeg-turbo
    - libavif
    - libpng
    - libdicom
    - openslide               


test:
  imports:
   - Iris
   - Iris.Codec
   - Iris.Encoder

about:
  home: https://github.com/IrisDigitalPathology/Iris-Codec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Portable and blazingly fast whole slide image compression and serialization library for the Iris File Extension
  dev_url: https://github.com/IrisDigitalPathology/Iris-Codec
  description: |
    The Iris Codec Community module is a part of the Iris Digital Pathology project. 
    This module allows for the reading and writing of Iris whole slide image (WSI) digital slide files (.iris) and 
    allows for the decoding of Iris Codec-type compressed tile image data. This repository was designed to allow 
    for extremely fast slide access using what we consider a very simple API as we want to simplify access to these
    files for you. Please see <https://github.com/IrisDigitalPathology/Iris-Codec> for more information.

extra:
  feedstock-name: Iris-Codec
  recipe-maintainers:
    - ryanlandvater
