{% set version = "2025.2.0a1" %}

package:
  name: iris-codec
  version: {{ version }}

source:
  url: https://github.com/ryanlandvater/Iris-Codec/archive/refs/tags/2025.2.0a2.tar.gz
  sha256: dd9067afdc397da98372a8d83e1f562ad852c3696427b31da27b7ce3eca810d1
  # url: https://github.com/IrisDigitalPathology/Iris-Codec/archive/refs/tags/2025.2.0a1.tar.gz
  # sha256: ce23d9b7bfc91281509d037641f969b02fb4fe235bc68b0059f793f2216a298a
build:
  number: 0
  run_exports:
    - {{ pin_subpackage('iris-codec', max_pin='x.x') }}
    - libjpeg-turbo
    - libavif
    - libpng
  missing_dso_whitelist:
    - '*/libopenslide.1.*' # Eventually remove reliance on OpenSlide


requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - cmake
    - make                    # [not win]
    - ninja                   # [win]
    - pybind11
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               # [not win]
  host:
    - python
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               # [not win]
  run:
    - python
    - libjpeg-turbo 3.0
    - libavif
    - libpng
    - openslide               # [not win]


test:
  imports:
   - Iris


about:
  home: https://github.com/IrisDigitalPathology/Iris-Codec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Portable and blazingly fast whole slide image compression and serialization library for the Iris File Extension
  dev_url: https://github.com/IrisDigitalPathology/Iris-Codec
  description: |
    The Iris Codec Community module is a part of the Iris Digital Pathology project. 
    This module allows for the reading and writing of Iris whole slide image (WSI) digital slide files (.iris) and 
    allows for the decoding of Iris Codec-type compressed tile image data. This repository was designed to allow 
    for extremely fast slide access using what we consider a very simple API as we want to simplify access to these
    files for you. Please see <https://github.com/IrisDigitalPathology/Iris-Codec> for more information.

extra:
  feedstock-name: Iris-Codec
  recipe-maintainers:
    - ryanlandvater
