github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
provider:
  linux_64: azure
  osx_64: azure
  win_64: azure
  linux_ppc64le: default
  linux_aarch64: default
test: native